"""drop refreshtokens table

Revision ID: 75c418d4db11
Revises: b1d097cfcc9b
Create Date: 2026-06-14 07:57:36.391016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c418d4db11'
down_revision: Union[str, Sequence[str], None] = 'b1d097cfcc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_replaced_by_token'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_reson_revoked'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_token'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('replaced_by_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reson_revoked', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refreshtokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refreshtokens_pkey'))
    )
    op.create_index(op.f('ix_refreshtokens_token'), 'refreshtokens', ['token'], unique=True)
    op.create_index(op.f('ix_refreshtokens_reson_revoked'), 'refreshtokens', ['reson_revoked'], unique=False)
    op.create_index(op.f('ix_refreshtokens_replaced_by_token'), 'refreshtokens', ['replaced_by_token'], unique=False)
    op.create_index(op.f('ix_refreshtokens_id'), 'refreshtokens', ['id'], unique=False)
    # ### end Alembic commands ###
