"""create table refreshtokens again

Revision ID: b1d097cfcc9b
Revises: df0e743f0cc9
Create Date: 2026-01-23 16:06:35.598081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d097cfcc9b'
down_revision: Union[str, Sequence[str], None] = 'df0e743f0cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_token', sa.String(), nullable=True),
    sa.Column('reson_revoked', sa.String(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtokens_id'), 'refreshtokens', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_replaced_by_token'), 'refreshtokens', ['replaced_by_token'], unique=False)
    op.create_index(op.f('ix_refreshtokens_reson_revoked'), 'refreshtokens', ['reson_revoked'], unique=False)
    op.create_index(op.f('ix_refreshtokens_token'), 'refreshtokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_token'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_reson_revoked'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_replaced_by_token'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_id'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    # ### end Alembic commands ###
